- sysctl: name=net.bridge.bridge-nf-call-ip6tables value=1 state=present reload=yes sysctl_set=yes
- sysctl: name=net.bridge.bridge-nf-call-iptables value=1 state=present reload=yes sysctl_set=yes
- name: install calico
  shell: >
    export KUBECONFIG=/etc/kubernetes/admin.conf ;
    curl --location "https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml" >/etc/kubectl/calico.yml ;
    kubectl apply -f /etc/kubectl/calico.yml
- shell: >
    export KUBECONFIG=/etc/kubernetes/admin.conf ;
    kubectl get pods -n kube-system -l k8s-app=calico-etcd
  register: result
  until: result.stdout.find("Running") != -1
  retries: 100
  delay: 10
- shell: >
    export KUBECONFIG=/etc/kubernetes/admin.conf ;
    kubectl get pods -n kube-system -l k8s-app=calico-kube-controllers
  register: result
  until: result.stdout.find("Running") != -1
  retries: 100
  delay: 10
