- name: initialize kube
  shell: >
    kubeadm reset ;
    kubeadm init --apiserver-advertise-address=10.0.0.10
  register: kubeadm_out
  create: /etc/kubeadm-join.sh
- lineinfile:
    path: /etc/kubeadm-join.sh
    line: "{{kubeadm_out.stdout_lines[-1]}}"
    create: yes
  when: kubeadm_out.stdout != ""
- file: path=/home/vagrant/.kube state=directory owner=vagrant
- file: src=/etc/kubernetes/admin.conf dest=/home/vagrant/.kube/config owner=vagrant
- lineinfile:
    path: /etc/profile
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
- service: name=kubelet state=started enabled=yes
- name: install weave net
  shell: >
    export kubever=$(sudo kubectl version | base64 | tr -d '\n') ;
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
- shell: kubectl get nodes master
  register: result
  until: result.stdout.find("Ready") != -1
  retries: 20
  delay: 5
