- selinux:
    state: disabled
- service: name=firewalld state=stopped enabled=no
- lineinfile: dest=/etc/sysctl.conf line='net.bridge.bridge-nf-call-ip6tables = 1' state=present
- lineinfile: dest=/etc/sysctl.conf line='net.bridge.bridge-nf-call-iptables = 1' state=present
- name: swap off and sysctl update
  shell: >
    swapoff -a ;
    sysctl -p ;
    touch /etc/swap-is-off
  args:
    creates: /etc/swap-is-off
- lineinfile: dest=/etc/fstab regexp='^/[\S]+\s+swap\s+swap ' state=absent
- name: fix kubelet config
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^(Environment="KUBELET_NETWORK_ARGS=).+"$'
    replace: '\1"'
- user: name=vagrant groups=dockerroot
- user: name=centos groups=dockerroot
- service: name=docker state=started enabled=yes
- service: name=ntpd state=started enabled=yes
- service: name=kubelet state=started enabled=yes
