- selinux: state=disabled
- service: name=firewalld state=stopped enabled=no
- sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes sysctl_set=yes
- name: swap off
  shell: >
    swapoff -a ;
    touch /etc/swap-is-off
  args:
    creates: /etc/swap-is-off
- lineinfile: dest=/etc/fstab regexp='^/[\S]+\s+swap\s+swap ' state=absent
- name: fix kubelet config
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^(Environment="KUBELET_NETWORK_ARGS=).+"$'
    replace: '\1"'
- user: name=vagrant groups=dockerroot
- user: name=centos groups=dockerroot
- service: name=docker state=started enabled=yes
- service: name=ntpd state=started enabled=yes
- service: name=kubelet state=started enabled=yes
