- yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    enabled: yes
- name: update packages
  yum: name='*' state=latest
- name: install docker
  yum: name={{ item }} state=present
  with_items:
    - docker
    - kubelet
    - kubeadm
    - kubectl
    - ntp
